### ISSUE TITLE
Curved paper lines

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/text-to-handwriting#1]
Currently, the lines on paper are straight. However usually when you scan a paper, the paper has folds and curves so it hardly looks exactly straight.

This is what it should look like instead (did this in photoshop)
![sample image with curved lines on paper](https://user-images.githubusercontent.com/30949385/77522561-7256ac80-6eaa-11ea-8da1-5a1015331744.png)

If anyone knows how can we achieve this using CSS, do let me know!

**Comment by anuraghazra** [comment]
You can probably try these methods

- Distort the html2canvas's canvas buffer
   - https://github.com/ericleong/fisheye.js
   - https://codepen.io/jOlga/pen/KyQMQW
- SVG curved paths? https://css-tricks.com/snippets/svg/curved-text-along-path/
- Applying CSS transform to each and every letter
   - https://stackoverflow.com/a/14990380/10629172

**Comment by saurabhdaware** [comment]
Woah! Thank you so much Anuraj! This is super useful. I will check it out :D

**Comment by saurabhdaware** [comment]
If anyone wants to try this out and help in making it, I've created a branch [feat-distortions](https://github.com/saurabhdaware/text-to-handwriting/tree/feat-distortions) where I'm trying out this distortion effect.

**Comment by subodhk01** [comment]
Hey I want to work on this issue, I love the idea of curved lines to add realism. Can I work??

**Comment by saurabhdaware** [comment]
Hi @subodhk01, Yes you can work on it! Thank you

**Comment by subodhk01** [comment]
Soo far I'm able to achieve this, any suggestions or comments???
NOTE: The curvature and the curve tip position is customisable. 

<img width="1112" alt="Screenshot 2020-05-09 at 17 03 09" src="https://user-images.githubusercontent.com/19875783/81472625-f83e7500-9216-11ea-88d9-db3f1ec5d28c.png">

**Comment by saurabhdaware** [comment]
This looks amazing!!

**Comment by saurabhdaware** [comment]
Resolved in #21
