### ISSUE TITLE
Text copy paste issue 

### ISSUE THREAD

**Issue by xansh** [saurabhdaware/text-to-handwriting#106]
When you copy some text and if in the there is '<' this bracket then the following word or line is not copied. 
![Q1(1) prob](https://user-images.githubusercontent.com/65403652/98378251-c6925380-206b-11eb-8b14-9799d12ad508.jpg)

#include < iostream >
This line should be pasted but instead of this it only shows 
#include
I have to write <iostream> separately or any thing which is followed by '<' .

In fact in this issue report page its not showing the word or line followed by '<', that is why I have to write < iostream > this with a space in between.
I m using this on chrome on my laptop.

**Comment by Drizl** [comment]
use safari or the darkweb especially sector 4 in the coding 9th projection

**Comment by saurabhdaware** [comment]
The words are actually limited and it depends on the font you're using. Some fonts support `<` and some don't and if it doesn't support that letter then the fallback is rendered.

If you want to use that bracket, unfortunately you will have to find a font that supports it.
