### ISSUE TITLE
Make this application more near to human handwriting (I have a suggestion for that).

### ISSUE THREAD

**Issue by Pratikmehta1729** [saurabhdaware/text-to-handwriting#111]
So what this application currently doing is its taking font file which has every character of any respective language and accordingly you replace all character with those character provided in the file but the problem is when a human writes something, In its handwriting not always same characters look exactly same, so what you can do is take 2 or 3 characters for each character and randomly distribute them while generating a handwritten image, this makes handwriting which is more near to human way of writing. By the way, it's an awesome application thanks to the contributors.

![autodraw 21_11_2020](https://user-images.githubusercontent.com/43946536/99878918-b6af6d80-2c2e-11eb-9ca8-98b4e38c4420.png)

**Comment by amaan-ahmad** [comment]
Hey @Pratikmehta1729, there is an option available for custom writing fonts that can be generated using [calligrapher](https://www.calligraphr.com/en/), it also randomizes the handwriting fonts.

**Comment by Pratikmehta1729** [comment]
@amaan-ahmad  great, thanks!
