### ISSUE TITLE
Supporting Re Ordering Images After They're generated

### ISSUE THREAD

**Issue by ForceGT** [saurabhdaware/text-to-handwriting#120]
Can we have a feature that allows drag and drop to reorder the images 

**USE CASE**
Sometimes it may happen that we need this because you may make a mistake in one page and create many pages after it
There is no way to undo other than deleting all of the other images

**Comment by saurabhdaware** [comment]
This sounds great! Keeping this open

**Comment by StTronn** [comment]
Hi Saurabh Can I take this issue?. Is it ok if I make Pr through the master/main branch?

**Comment by saurabhdaware** [comment]
yes @StTronn that would be great help! Let me know if you need any help (though I am not very active so I may reply late)

**Comment by StTronn** [comment]
Cool, I have made pull request #125 let me know of changes whenever you are free.
