### ISSUE TITLE
PDF Preview before downloading

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/text-to-handwriting#19]
Currently, as you generate an image, the image goes on getting added into PDF that you can download. so when you click "download as pdf" it directly downloads the PDF. 

It would be cool if we get a screen with all the generated images displayed, from where you can delete the image that you don't need and then download it as PDF.

Sorry for the bad drawing :c
![a flow diagram that shows clicking preview pdf should open a screen where you can remove pictures and finalize PDF before downloading](https://user-images.githubusercontent.com/30949385/80881802-2af9e200-8cda-11ea-952a-03c6e4819d45.jpg)

**Comment by nairaalam** [comment]
Also, how can I get rid of the scanned by Anonymous Scanner text which keeps getting added to each pdf file? Is there a toggle?

**Comment by saurabhdaware** [comment]
Hi @nairaalam, once we get the PDF preview feature we can add a way to change that text, until then I've removed that text (9da4f8d76ef45bdbc9082ca3026daffa3f0aac88). Makes sense to not have anything there. Thanks!
