### ISSUE TITLE
Paste without formatting while keeping the line-breaks same

### ISSUE THREAD

**Issue by kenilpatepy** [saurabhdaware/text-to-handwriting#23]
please upgrade it for directly copy and pest

**Comment by saurabhdaware** [comment]
In initial versions, it was possible to paste the content without formatting but when users used to paste without formatting it also removed the line-breaks so we had to roll-back that change. If there is any way we can paste without formatting and still keep the line-breaks, we would love to implement that.

**Comment by saurabhdaware** [comment]
Resolved in ecffc2e
