### ISSUE TITLE
unable to convert inspite of having a ttf file.Pls help!

### ISSUE THREAD

**Issue by sagar-17** [saurabhdaware/text-to-handwriting#27]
<img width="788" alt="qa" src="https://user-images.githubusercontent.com/66031001/83057471-8e2a2a80-a074-11ea-935e-b84352d3b8da.PNG">

**Comment by saurabhdaware** [comment]
Hi can you mention which browser you're using?

**Comment by sagar-17** [comment]
> Hi can you mention which browser you're using?

the issue got resolved.
Also, could youtell how do i get this baseline alignment right,in the image,letters are a bit elevated from the line?[](url)

**Comment by sagar-17** [comment]
<img width="318" alt="42" src="https://user-images.githubusercontent.com/66031001/83132298-cf671c80-a0fe-11ea-915b-81c68f78e016.PNG">
![Uploading 113.jpg…]()

**Comment by saurabhdaware** [comment]
Hi, there is "vertical position of text" option on the website, you can change its value to adjust the text vertically

![screenshot of text to handwriting tool](https://user-images.githubusercontent.com/30949385/83149476-c20a5c00-a117-11ea-83e2-d760b0bb73f3.png)

**Comment by saurabhdaware** [comment]
Marking it as resolved, let me know if there's anything else I can help with. Thank you!

**Comment by sagar-17** [comment]
Thank you so much !
I’ll try it.

**Comment by sagar-17** [comment]
Yeah cool!
Thanks
