### ISSUE TITLE
Camscanner output

### ISSUE THREAD

**Issue by subins2000** [saurabhdaware/text-to-handwriting#30]
Most people use the `Camscanner` app to scan paper. It has a filter which makes the image black & white-ish & increase contrast or something. The output is very distinguishable.

Adding that filter to this output will help pass the output more as our assignment.

**Comment by saurabhdaware** [comment]
That's a great suggestion!!! Maybe we can have an Effect form field with a dropdown and possible effects.

**Comment by subodhk01** [comment]
And also we can have some custom watermarks, like Camscanner's water, its would make the image more realistic.

**Comment by ahmadawais** [comment]
An effects from field and also the ability to remove all effects would be great.

**Comment by saurabhdaware** [comment]
Thank you all for suggestions! I'm working on this and this will be added along with the new design. (branch: [redesign](https://github.com/saurabhdaware/text-to-handwriting/tree/redesign))

**Comment by saurabhdaware** [comment]
Added a dropdown in #54 , Currently it only has "Shadows" and "No effects".

**Comment by pathakshashank17** [comment]
Hey,
I would like to contribute to this issue by adding an effect similiar to CamScanner. Click on the links to view the samples that I was able to create : 
- [No Contrast](https://user-images.githubusercontent.com/64695775/86949615-8d54e000-c16c-11ea-9240-f66e40694bc0.jpg)
- [50% Contrast](https://user-images.githubusercontent.com/64695775/86949661-9c3b9280-c16c-11ea-83bf-560b853303ce.jpg)
- [70% Contrast](https://user-images.githubusercontent.com/64695775/86949724-b4131680-c16c-11ea-8734-59050dda4d08.jpg)

I would love to add this effect ! I request to be assigned this issue.

**Comment by saurabhdaware** [comment]
> Hey,
> I would like to contribute to this issue by adding an effect similiar to CamScanner. Click on the links to view the samples that I was able to create :
> 
>     * [No Contrast](https://user-images.githubusercontent.com/64695775/86949615-8d54e000-c16c-11ea-9240-f66e40694bc0.jpg)
> 
>     * [50% Contrast](https://user-images.githubusercontent.com/64695775/86949661-9c3b9280-c16c-11ea-83bf-560b853303ce.jpg)
> 
>     * [70% Contrast](https://user-images.githubusercontent.com/64695775/86949724-b4131680-c16c-11ea-8734-59050dda4d08.jpg)
> 
> 
> I would love to add this effect ! I request to be assigned this issue.

aaaaaaaaa THIS IS SOOOOOOO COOOOL!!!!! YES YES GO AHEAD!

**Comment by subodhk01** [comment]
@pathakshashank17 It looks great!!

**Comment by saurabhdaware** [comment]
Thank you for the suggestion @subins2000, its added now (thanks to @pathakshashank17) 🎉
