### ISSUE TITLE
Adding some more natural handwritten like fonts

### ISSUE THREAD

**Issue by abhijithvijayan** [saurabhdaware/text-to-handwriting#31]
Super cool project. Requires some ui tweaks.

Some fonts exhibit over spacing in between of words.

**Comment by saurabhdaware** [comment]
Thank you @abhijithvijayan, That's a great suggestion but we can currently download fonts from google fonts and upload them with the upload button.

![screenshot that shows the upload button on tool](https://user-images.githubusercontent.com/30949385/83228931-adc07080-a1a4-11ea-8e35-30b45140c7ac.png)

and about the word-spacing, it can be adjusted with the letter spacing and word spacing option in the tool.

I am closing this for now,  let me know if you have any other thoughts.

Thank you!

**Comment by abhijithvijayan** [comment]
I had issues with spacing issues with fonts from other sites.

Word spacing didnt change a thing anyway.

**Comment by saurabhdaware** [comment]
Yes, there are some [font spacing issues in the html2canvas library](https://github.com/niklasvh/html2canvas/issues/2190) that we use and thus as a workaround, we have letter-spacing and word-spacing option. Though it doesn't output the exact same results as the input, adjusting these values can give readable results. 

This is the output of indieflower when I tried,
![indieflower output in tool](https://user-images.githubusercontent.com/30949385/83229506-b9606700-a1a5-11ea-984d-a39723b754df.png)

If letter-spacing and word-spacing are not working for you, can you tell which browser you're trying on?

**Comment by abhijithvijayan** [comment]
It's not these 2 fonts that exhibit the issue.

As I suggested before, those 2 work very well. A couple of handwriting fonts I tried from other sites had those issues.

 Will try to attach those sometime later.
