### ISSUE TITLE
Allow custom pages with college logos and different format

### ISSUE THREAD

**Issue by annaxds1202** [saurabhdaware/text-to-handwriting#32]
Certainly what you are doing is way too much for us, but as the greed increases for perfection can you add the option to add our assignment pages as it includes the logo of our college and would look a little more closer to legitness .. thanks btw :)

**Comment by subodhk01** [comment]
@annaxds1202 Great suggestion, can you share a template of how the assignment page looks like?

**Comment by saurabhdaware** [comment]
I think PR #35 can solve this issue, it will allow users to add logo to the page.

**Comment by subodhk01** [comment]
I think it would be great if the images can also serve as an overlay rather than just being images besides the text content.
Coz this way we can have watermarks or custom page borders anywhere and of any opacity we want.

**Comment by saurabhdaware** [comment]
By watermark do you mean a watermark on paper?

**Comment by subodhk01** [comment]
Yeah either that or having options to add frames on the images.

**Comment by saurabhdaware** [comment]
Yes yes makes sense to have a background which you can write over

**Comment by Manaswini1832** [comment]
Hey Saurabh! I'd like to work on this issue. Could you assign me to it?

**Comment by saurabhdaware** [comment]
Sure @Manaswini1832 Go ahead :D
