### ISSUE TITLE
why is this happening?

### ISSUE THREAD

**Issue by sagar-17** [saurabhdaware/text-to-handwriting#33]
<img width="816" alt="sag" src="https://user-images.githubusercontent.com/66031001/83283476-e9852580-a1f8-11ea-8b8d-9f1fc84c49b8.PNG">

**Comment by saurabhdaware** [comment]
Can you try, right click -> paste as plain text instead of direct paste?

**Comment by sagar-17** [comment]
No it’s not working.
Also I first take the text in MS word and convert into the required font
and copy it from there and then paste it on your site.

**Comment by saurabhdaware** [comment]
It might be happening because of that then, may I know why not just paste directly into the textarea? you can add font from the website itself

**Comment by sagar-17** [comment]
Issue resolved

**Comment by saurabhdaware** [comment]
cool! thanks
