### ISSUE TITLE
Resize the image and move in around the page.

### ISSUE THREAD

**Issue by imrishabh18** [saurabhdaware/text-to-handwriting#34]
**Is your feature request related to a problem? Please describe.**
I am having issue putting the image on the page as I can't resize the image or move it around and place it as per my choice.

**Comment by saurabhdaware** [comment]
As a workaround for now, you can move image by adding space before the image (the way you would position a text) but yes I agree it's complicated and not the best UX.  And the resize is absolutely not possible!

Thanks Rishabh, I am keeping this open if anyone wants to work on this

**Comment by Himanshunitrr** [comment]
I will like to work on this sir.

**Comment by saurabhdaware** [comment]
Hi Himanshu, Can you choose one of the #34, #62, #68? It will be difficult to work on all 3 of them at the same time and while you're working on one PR, if someone else wants to contribute to other Issues, we can give them chance as well.

If no one else claims the other issues while you're working on one, after completing one you can tackle them as well if you want.

Let me know which one you want to work on

**Comment by Himanshunitrr** [comment]
I will like to complete the incomplete first. (#62 )

**Comment by saurabhdaware** [comment]
Cool you can go ahead with it 🎉

**Comment by aancoeg** [comment]
you can easly change the renderen image resolution in \css\index.css on .page-a (line 191 and 192)
you can input your image resolution there, save tehe file, and restart the program
