### ISSUE TITLE
Adding page number to the pdf

### ISSUE THREAD

**Issue by DhruvDoshi** [saurabhdaware/text-to-handwriting#36]
**Is your feature request related to a problem? Please describe.**
Well this is the great product but with this I got some greedy and I want to have some page number marking at the end of the page or in the header or the footer of the page!

**Describe the solution you'd like**
Well I came across some python code which you could use which I had developed in the previous project along with that I would suggest a package name "pdfrw", you can install it with pip and then It could solve major of the problem.

**Describe alternatives you've considered**
The code I am attaching along with idea to use pdfrw

![Screenshot (5)](https://user-images.githubusercontent.com/41964565/83328864-d4190580-a2a3-11ea-9645-a6afe4eec4d0.png)
![Screenshot (6)](https://user-images.githubusercontent.com/41964565/83328866-d5e2c900-a2a3-11ea-8c58-3ff7aa7b0c6e.png)
![Screenshot (7)](https://user-images.githubusercontent.com/41964565/83328867-d67b5f80-a2a3-11ea-8039-a7f3cec9018e.png)

Along with that adding that code with Zip file too
[pg_no.zip](https://github.com/saurabhdaware/text-to-handwriting/files/4705645/pg_no.zip)

**Additional context**

**Comment by saurabhdaware** [comment]
I'm not sure if I get what you're trying to suggest but currently we can write page numbers like this
![An output from text to handwriting that has page number written on bottom with same font as the writing font](https://user-images.githubusercontent.com/30949385/83333892-937bb500-a2c0-11ea-92dc-16be65bfa80c.png)

**Comment by saurabhdaware** [comment]
Ok so reading the code I guess you mean adding page numbers to PDF? That will be a little out of context to what this tool is trying to do. 

Usually, when you write an assignment, click a picture, and generate PDF, it will generate a PDF without page number only.

For such edge cases, you can download as an image and generate PDF in any other PDF generator that adds the page numbers.

Let me know if there's something I've misunderstood and I will reopen it.
