### ISSUE TITLE
Addition of underline feature

### ISSUE THREAD

**Issue by SubhroRusso** [saurabhdaware/text-to-handwriting#42]
Please add underline feature also if possible. Both wavy and normal underlining.

**Comment by saurabhdaware** [comment]
That would be a great addition but the problem with underline is, the lines will be too straight to look real. There are similar issues with strikethrough and other font features as well. Plus some fonts are not supporting the underline so the overall impact of underline toggle will be inconsistent and won't work with lots of fonts. 

As a workaround, you can select the font you want to underline and press `CTRL + U`

If we find a way we can make underlines look more real, I will reopen this. Thank you!
