### ISSUE TITLE
Adjust the degree of font clutter

### ISSUE THREAD

**Issue by Pil0tXia** [saurabhdaware/text-to-handwriting#43]
Handwritting has many skewings, enabling users to adjust themselves' font clutter may be quite useful for a more authentic copy.
Here is a website which did well in this case <www.beautifulcarrot.com>, but it is not free to download the original file. 
Hope you will make out a better product subsituting this site!

**Comment by saurabhdaware** [comment]
I can't visit the site you've mentioned. By font clutter do you mean uglifying the font in some places? In that case, it will be dependent on the font. There are font generating websites which let you generate optional characters in the font and when you use the font, it will randomly add these optional characters. 

So we can't really do much to font from our side. Let me know if I've misunderstood something and I will reopen this issue.

Thank you :D
