### ISSUE TITLE
Improved UI Proposal

### ISSUE THREAD

**Issue by anuraghazra** [saurabhdaware/text-to-handwriting#55]
Hey @saurabhdaware i have redesigned some form elements and created a wireframe of the new design. let me know what you think about it.

<img width="695" alt="text-to-handwriting-ui" src="https://user-images.githubusercontent.com/35374649/85927383-4f7dcf00-b8c3-11ea-8a3d-05fae40b519c.png">

**Comment by saurabhdaware** [comment]
This looookss amazingggggggg aaaa soo coool 😭😭😭

**Comment by saurabhdaware** [comment]
I'll keep this open if someone wants to work on this! I'm kinda 💩 in css :c

**Comment by anuraghazra** [comment]
Thanks! :D glad you liked it. well i can do it in a day or so. if i have time i'll do a PR and let you know. :smile:

**Comment by saurabhdaware** [comment]
Yes yes sure sure Thank youuu!

**Comment by anuraghazra** [comment]
@saurabhdaware close it probably?

**Comment by saurabhdaware** [comment]
whoop whoop forgot! Resolved in #57
