### ISSUE TITLE
Scrolling preview image bug in mobile view

### ISSUE THREAD

**Issue by RinkiyaKeDad** [saurabhdaware/text-to-handwriting#59]
**Describe the bug**
Scrolling the preview image in mobile view also scrolls the the Heading Text ("Input"), Sub heading ("Type/Paste text here") and the Button ("Draw(Beta)").

**To Reproduce**
1. Switch to mobile view
2. Right swipe on the preview image
3. You'll see that the headings and buttons are now not visible.

**Expected behavior**
The headings and button should remain despite you chosing to scroll through the image.
![Error1](https://user-images.githubusercontent.com/56963264/86246680-041c3700-bbc9-11ea-8f97-bc4dac941545.png)
![Error2](https://user-images.githubusercontent.com/56963264/86246688-07172780-bbc9-11ea-95eb-52782c5ed2e8.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
Although a minor bug but it'd be great if the behaviour was as expected.

**Comment by saurabhdaware** [comment]
Thanks! #60
