### ISSUE TITLE
Adding some other languages

### ISSUE THREAD

**Issue by Himanshunitrr** [saurabhdaware/text-to-handwriting#62]
**Is your feature request related to a problem? Please describe.**
{
     I think it will be more helpful if we can provide support in other languages specially hindi.
     It will help a lot of students !
}
**Describe the solution you'd like**
{
      Well in too short I want to help my younger brother who has hindi as subject. 
      Its just an extension of languages you provide sir. More languages mean more help 
      as your application will have than a much broader audience.
}
**Describe alternatives you've considered**

**Additional context**

**Comment by Himanshunitrr** [comment]
Calligraphr only supports English Deutsch Español Français

**Comment by saurabhdaware** [comment]
I would love to add that but I couldn't find any hindi font that looks close to handwriting, I'll see once again and if anyone knows a font that supports hindi and looks like handwriting, let me know here.

**Comment by Himanshunitrr** [comment]
I will make one using mine own handwriting. Here's a link by which i will make one.
https://www.youtube.com/watch?v=-iytzhx1SdU
Will love to do this

**Comment by saurabhdaware** [comment]
THAT WOULD BE AMAZING! Thank you so much

**Comment by Himanshunitrr** [comment]
So I should start. Will keep informing you 
Thanks!!!

**Comment by saurabhdaware** [comment]
Yes you can go ahead

**Comment by Himanshunitrr** [comment]
Sorry for the late response( unexpected online practicals started ). I have build the font. Will upload here after giving it the final touch.

**Comment by saurabhdaware** [comment]
Sure! and no need to say sorry its open-source so you can work with your own timeline :D

**Comment by Himanshunitrr** [comment]
I have created the fonts. But the problem with Hindi is that people use qwerty keyboard to type Hindi, so mine fonts will work only when you type in keyboard and not when you copy-paste, Will develop that fonts too (calligraph has not all alphabets available for the Hindi language). But if someone wants to type then he/she can use this font sir.

**Comment by Himanshunitrr** [comment]
Sent the fonts to your mail sir.

**Comment by saurabhdaware** [comment]
> I have created the fonts. But the problem with Hindi is that people use qwerty keyboard to type Hindi, so mine fonts will work only when you type in keyboard and not when you copy-paste, Will develop that fonts too (calligraph has not all alphabets available for the Hindi language). But if someone wants to type then he/she can use this font sir.

That's great! we'll find a workaround for paste text later. Will you be interested in sending PR to add that font in defaults?

We can create `fonts` folder in root, include font into page, and then in https://github.com/saurabhdaware/text-to-handwriting/blob/master/index.html#L219 we can add a new option for that font with `value=""` as the name of font.

Let me know if you're interested to work :D 

P.S. Don't call me sir 😂

**Comment by Himanshunitrr** [comment]
For sure
