### ISSUE TITLE
Adding transition effects to dark/light theme changes

### ISSUE THREAD

**Issue by pathakshashank17** [saurabhdaware/text-to-handwriting#64]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It it would be nice if theme changes are accompanied by transitions into each other. I know this request might sound like too small, but I think it would add little more elegance into the website.

**Additional context**
I would love to add the above changes ! Should I do so ? I am new to GitHub, so should I send a PR first or wait for this issue to get assigned ?

**Comment by saurabhdaware** [comment]
Hi Shashank and yes that would be great! you can go ahead with it. Let me know if you need any help :D!
