### ISSUE TITLE
Font Suggestions

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/text-to-handwriting#78]
If you know any font that looks like handwriting, you can suggest them here and we may consider adding it to the tool

**Comment by GouravSwamy** [comment]
you must give a try this font it looks like handwritten 
i have attached below the zip of the font do check it out
font name candia_script 
[candia_script.zip](https://github.com/saurabhdaware/text-to-handwriting/files/5048173/candia_script.zip)

**Comment by souranild** [comment]
https://www.quantumenterprises.co.uk/handwriting-fonts/fontvault.htm
you can use every font here. all are free to use and are very realistic! cheers!

**Comment by saurabhdaware** [comment]
> https://www.quantumenterprises.co.uk/handwriting-fonts/fontvault.htm
> you can use every font here. all are free to use and are very realistic! cheers!

THIS IS AMAZING! Thank you @sournail I'll check it out

**Comment by mayanktiwari21** [comment]
Its amazing..the only issue I m facing is that the text is not covering the whole page...

**Comment by saurabhdaware** [comment]
Hi @mayanktiwari21 , Can you create another issue with a screenshot?

**Comment by cheenuprince** [comment]
![download (44)](https://user-images.githubusercontent.com/68725358/94050778-59489d00-fdf4-11ea-969d-4169493905fa.jpg)
Help me its not using full page

**Comment by cheenuprince** [comment]
![Uploading download (45).jpg…]()

**Comment by dev2919** [comment]
![image](https://user-images.githubusercontent.com/48598352/96695852-c0cc1b00-13a7-11eb-89fe-a1234bb34b24.png)

here's another font 
[here](https://anonymousfiles.io/i9PixIP2/)

**Comment by AmazingKeymaster** [comment]
Hey pls add this font plss. I have like a trilion pdfs to write o it will be a great help if you could ad this font
![IMG_20201028_214639](https://user-images.githubusercontent.com/73605411/97468965-dfb04b80-196b-11eb-9902-d12d00300120.jpg)

**Comment by Raju1611** [comment]
![2C1C7C3A-DAC4-4689-8F58-39E10D76325C](https://user-images.githubusercontent.com/74810865/99870183-1c3e3280-2c0c-11eb-8b43-6ce0f3800976.jpeg)

Please add my handwritings in your website. I need this bro. Please. Please. Please. Love you from Bangladesh.

**Comment by lovneet4013** [comment]
Hii saurabh , i can provide you lots of fonts from https://www.quantumenterprises.co.uk/handwriting-fonts premium paid fonts and other sources which looks closest to handwriting, so that you can add all those in your resources and provide poor students tons of  customization without struggling on web

**Comment by ForceGT** [comment]
> Hii saurabh , i can provide you lots of fonts from https://www.quantumenterprises.co.uk/handwriting-fonts premium paid fonts and other sources, so that you can add all those in your resources and provide poor students tons of more customization without struggling on web 

Just make sure there are no copyright issues, because piracy is not encouraged at all and might affect the project badly

**Comment by ForceGT** [comment]
Hey @saurabhdaware can we make some mechanism to let anybody add any font (maybe have a small static storage or something) and just have some approval to check if that font is really useful
That way we can have a collection of actual handwriting like fonts 
I am up if you need someone for approval

**Comment by lovneet4013** [comment]
> > Hii saurabh , i can provide you lots of fonts from https://www.quantumenterprises.co.uk/handwriting-fonts premium paid fonts and other sources, so that you can add all those in your resources and provide poor students tons of more customization without struggling on web
> 
> Just make sure there are no copyright issues, because piracy is not encouraged at all and might affect the project badly

If that is the issue ,than i can provide a way to do it by user itself instead of processed fonts or other ways to use them without triggering their privacy policy. i also want best for this project and bring it to next lvl ;)

**Comment by ForceGT** [comment]
> > > Hii saurabh , i can provide you lots of fonts from https://www.quantumenterprises.co.uk/handwriting-fonts premium paid fonts and other sources, so that you can add all those in your resources and provide poor students tons of more customization without struggling on web
> > 
> > 
> > Just make sure there are no copyright issues, because piracy is not encouraged at all and might affect the project badly
> 
> If that is the issue ,than i can provide a way to do it by user itself instead of processed fonts or other ways to use them without triggering their privacy policy. i also want best for this project and bring it to next lvl ;)

Sure go ahead why not

**Comment by saurabhdaware** [comment]
We already have a way to add custom fonts. 

This is what you are talking about right? 
![Upload your handwritten font (BETA)](https://user-images.githubusercontent.com/30949385/100351785-02d52600-3012-11eb-882e-ec79168e6a17.png)

You can download fonts from any website you like and use this upload button to use it in tool. 

This thread is for suggesting fonts so that you can download and use it. And if there is any font that a lot of people are liking, then we can add it directly to the tool so users won't have to download.

**Comment by saurabhdaware** [comment]
My bad I should've cleared it while creating issue. Closing this issue for now.

**Comment by ExploJil711** [comment]
Hello @saurabhdaware . Is this a good ttf file? It just kinda look handwritten but a lil bit messed up.
https://drive.google.com/file/d/1KsUiscC_AqQE69X3ariS_7ah0H2G846X/view?usp=sharing
