### ISSUE TITLE
Resize added image

### ISSUE THREAD

**Issue by AmanRaj1608** [saurabhdaware/text-to-handwriting#80]
**Is your feature request related to a problem? Please describe.**

I want to resize the added image, added by the draw button. 
I am not sure if there is any other option available to resize it so I am using dev tools to add custom CSS.

**Describe the solution you'd like**
If there could be any slider for having setting width and height of the image added. 😅

**Describe alternatives you've considered**
An alternative method is to just add custom CSS and position it properly.

**Additional context**

![image](https://user-images.githubusercontent.com/42104907/89390687-b3967d00-d724-11ea-804b-75198c15041f.png)

**Comment by saurabhdaware** [comment]
Hi Aman, yes there isn't any other option available yet but would definitely love to have a way to do this.

Closing this issue since we have issue open for this in #34.

Thank you for reporting :D
