### ISSUE TITLE
code in contribution guide gives an error on Cmd and Powershell .

### ISSUE THREAD

**Issue by GouravSwamy** [saurabhdaware/text-to-handwriting#83]
**Describe the bug**

Steps 1 involved in contribution guide need a change
we followed steps written in contribution guide gives an 400 error as below:
fatal: unable to access 'https://github.com/:GouravSwamy/text-to-handwriting/': The requested URL returned error: 400

**Expected behavior**
contribution guide need edits.

correction :- git clone 'https://github.com/:your-github-username/text-to-handwriting.git'
please add another step do fork and then use your github username to successfully run the program.

the step 1 in contribution guide need .git at the end to successfully clone project to the pc.
correct the steps in contribution guide 
rest of the steps are absolutely correct.

**Screenshots**
![text-to-handwriting](https://user-images.githubusercontent.com/52397444/89738854-72da9300-da99-11ea-939c-ba19757e2cdc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Additional context**
Thanks for such an amazing project
glad to help you
regards
Gourav Swamy
check the attached screenshoot
![solved](https://user-images.githubusercontent.com/52397444/89738941-3d827500-da9a-11ea-8999-6d1986fcc240.jpg)

**Comment by saurabhdaware** [comment]
Hi Gourav, I believe the issue is with `:` before the username and not with `.git`. Can you check if `git clone https://github.com/GouravSwamy/text-to-handwriting` works?
