### ISSUE TITLE
pdf support

### ISSUE THREAD

**Issue by rahgurung** [saurabhdaware/text-to-handwriting#85]
I'm always frustrated when I have to manually download the images and then convert them into pdf.

Would be great to have a button which can convert the copies into a single pdf file.

**Comment by saurabhdaware** [comment]
Hii you can download it as PDF. There is download as PDF button in tool
![Screenshot that shows download images as PDF butto ](https://user-images.githubusercontent.com/30949385/90092814-8f9bf280-dd47-11ea-89c0-3ec815511ed2.png)

You can also generate multiple images at once by adding larger text that overflows from page

**Comment by rahgurung** [comment]
works
