### ISSUE TITLE
there should be button to clear all the generated image

### ISSUE THREAD

**Issue by rahgurung** [saurabhdaware/text-to-handwriting#89]
with one snap*

**Comment by Rishika1416** [comment]
@saurabhdaware we are a team of developers, we would like to work upon this issue#89. Can we proceed?

**Comment by saurabhdaware** [comment]
Hi, sure you can go ahead! let me know if you need any help (I am on a break right now so I may take time to respond) 

Thanks

**Comment by Rishika1416** [comment]
@saurabhdaware we are working on the issue #89 .we would also like to add the feature to have multiple pen colour in the same page that was already an issue raised by someone. Can we work on that?

**Comment by rahgurung** [comment]
Yeah, a PR can never be a problem. I think these two should be two different PRs independent of each other.

**Comment by Rishika1416** [comment]
@saurabhdaware Could you please share the acceptance test criteria so that we can work with better efficiency and understand what do you expect after this issue is resolved.

**Comment by saurabhdaware** [comment]
We can have a button with "Clear all images" text maybe in red color border (?) probably beside "Output" headline or next to Download All Images button. On click of that button, All generated images should be removed.

These are all my opinions ^^ if you feel something else would work better, let me know. Thanks!

**Comment by bit-shashank** [comment]
@Rishika1416  Are you working on this feature?

**Comment by rahgurung** [comment]
Of course not, I guess. Its been 20+ days, feel free to take up the issue. @bit-shashank

**Comment by Rishika1416** [comment]
we are working on this issue

**Comment by Rishika1416** [comment]
**@saurabhdaware** one of my teammate ShivamMundhra has sent you the pull request. Plz review it and let me know if any changes need to be done.
