### ISSUE TITLE
Dark Mode Causing The Generated Page Image To Go Out Of The Margins. 

### ISSUE THREAD

**Issue by hrichiksite** [saurabhdaware/text-to-handwriting#92]
**Describe the bug**
Dark Mode Causing The Generated Page Image To Go Out Of The Margins. 

**To Reproduce**

![Text to Handwriting](https://user-images.githubusercontent.com/57860916/91160893-a0ede300-e6e7-11ea-9f72-b3c31c5c0b9d.gif)

**Desktop:**
![image](https://user-images.githubusercontent.com/57860916/91161158-0215b680-e6e8-11ea-95e9-9a1b19bbe844.png)

https://www.whatsmybrowser.org/b/05UDH

**Comment by saurabhdaware** [comment]
Oh yes I've seen this happening but I couldn't figure out what is causing this issue. Apparently, even in dark mode, it sometimes works correct and sometimes pushes image. 

I tried with light mode and yup it is not happening in light mode.

Thank you for reporting!
