### ISSUE TITLE
Add folds and inaccuracies to page

### ISSUE THREAD

**Issue by AliasgarMukhi** [saurabhdaware/text-to-handwriting#94]
Hey, it is good to see that this thing actually works extremely smooth and i really appreciate the effort you put into this. But i want to ask from you that is there anything you can do to make these pages look less perfect??

I mean i did submitted the assignment but unfortunately my faculty was just too smart to caught me 😂 anyway but if there is something you could suggest me to edit the quality of pages or maybe introduce a random sequence of pages that'll look genuine.
These are too good to be true if you know what i mean.
If there's a way please do reply I'll really appreciate that!

**Comment by saurabhdaware** [comment]
I just had an idea of doing this! Lemme see if it works :D

**Comment by saurabhdaware** [comment]
oh oh we can already do this! Thank to #100 . You can click picture of a blank paper and upload it from the Upload Paper as Background option.
